version: "3.1"

services:
  db:
    image: mysql
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
