version: "3.1"

services:
  website:
    build: .
    volumes:
      - ./website:/var/www/html/
    ports:
      - 8080:80
    links:
      - db
    networks:
      - default

  db:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_USER_PASSWORD=test
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin
    links:
      - db:db
    ports:
      - 8000:80
